baseURL: "https://degaulmyn.github.io" 
title: Héloïse de Gaulmyn
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Resume
          url: resume/
          weight: 3 

params:
    description: "This website hosts Héloïse de Gaulmyn's research papers, curriculum vitae, and contact information."
    author: Héloïse de Gaulmyn
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","teaching","resume"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Héloïse de Gaulmyn
          subtitle: "I am a Ph.D Candidate in the Center for Research in Economics and Statistics (CREST) at École Polytechnique, France. I work in environmental economics. I am particularly interested in how energy mixes choice form and what are their implications in the global economy."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: Resume
              url: resume/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:heloise.de_gaulmyn@ens-paris-saclay.fr
        - name: Zoom
          url: https://zoom.us/launch/chat?src=direct_chat_link&email=heloise.de-gaulmyn%40polytechnique.edu
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/degaulmyn

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Héloïse de Gaulmyn"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
